[uwsgi]
chdir = /app
umask = 002
uid = django
gid = django
http-socket = :8080
env = HOME=/web
env = DJANGO_SETTINGS_MODULE=demoapp.settings
env = DJANGO_DEPLOYED=1
module = demoapp.wsgi:application
buffer-size = 32768
static-map = /static=/app/staticfiles
static-map = /media=/app/workdir/media
static-expires = /* 3600
offload-threads = %k
post-buffering = 1
processes = 2
threads = 2
master = true
thunder-lock = true
