# Generated by Django 5.1 on 2024-11-05 14:42

from django.db import migrations, models

import sendmail.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True, validators=[sendmail.validators.validate_email_with_name], verbose_name='Email From')),
                ('first_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True, verbose_name='Gender')),
                ('preferred_language', models.CharField(blank=True, default='', help_text='Users preferred language', max_length=12, verbose_name='Language')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is blocked')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
