# Generated by Django 5.1.3 on 2024-11-11 15:18

from django.db import migrations, models

import sendmail.validators


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemailaddress',
            name='email',
            field=models.CharField(max_length=254, unique=True, validators=[sendmail.validators.validate_email_with_name], verbose_name='Email'),
        ),
    ]
