# Generated by Django 5.1.3 on 2024-12-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customemailaddress_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customemailaddress',
            options={'verbose_name': 'Custom User'},
        ),
    ]
