# Generated by Django 5.1.3 on 2024-12-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_alter_customemailaddress_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customemailaddress',
            table='custom_email_address',
        ),
    ]
